title: UCSD Parking Data Research
description: Parking Availability analysis within Gillman and Hopkins Parking Structures at UCSD.
theme: just-the-docs

url: https://dsethanvo.github.io/UCSDParkingAnalysis/

nav:
  - title: "Home"
    url: "/"
  - title: "Collection and Cleaning"
    url: "/data/"
  - title: "Visualization"
    url: "/visualization/"
  - title: "Analysis"
    url: "/analysis/"

aux_links: 
  View on Github: https://github.com/dsEthanVo/UCSDParkingAnalysis
