title: UCSD Parking Data Research
description: Parking Availability analysis within Gillman and Hopkins Parking Structures at UCSD.
theme: just-the-docs

url: https://dsethanvo.github.io/UCSDParkingAnalysis/

nav:
  - title: "Home"
    url: "/"
    nav_order: 1
    
  - title: "Collection and Cleaning"
    url: "/data/"
    nav_order: 2
    
  - title: "Visualization"
    url: "/visualization/"
    nav_order: 3

  - title: "Analysis"
    url: "/analysis/"
    nav_order: 4


aux_links: 
  View on Github: https://github.com/dsEthanVo/UCSDParkingAnalysis
